name: Build and Check
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    uses: 
  check:
    needs: build
    name: Check
    uses: 
  publish:
    needs: build
    name: Publish (Logius)
    uses: 
    secrets: inherit
